# Generated by Django 6.1.1 on 2026-10-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.PositiveIntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
